import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BadgeCheck, BarChart3, BriefcaseBusiness, CalendarClock, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, ImagePlus, LayoutDashboard, LoaderCircle, LogOut, MapPin, Pencil, Plus, Save, Settings2, Store, TrendingUp, UserRound, UsersRound, X } from 'lucide-react';
import { getApiErrorMessage } from '../lib/api';
import { prepareImageUpload } from '../lib/imageUpload';
import { platformApi } from '../services/platformApi';
import type { BookingRecord, Practitioner, ScheduleRule, SupplierProfile } from '../types';
import { SupplierStorePage } from './SupplierStorePage';

type DashboardTab = 'overview' | 'store' | 'bookings' | 'team' | 'schedule';
const days = [['MONDAY', 'Thứ Hai'], ['TUESDAY', 'Thứ Ba'], ['WEDNESDAY', 'Thứ Tư'], ['THURSDAY', 'Thứ Năm'], ['FRIDAY', 'Thứ Sáu'], ['SATURDAY', 'Thứ Bảy'], ['SUNDAY', 'Chủ Nhật']] as const;
const defaultRules = (): ScheduleRule[] => days.map(([day]) => ({ dayOfWeek: day, startTime: '09:00', endTime: '18:00', breakStart: '12:00', breakEnd: '13:00', slotMinutes: 30, active: day !== 'SUNDAY' }));

export const SupplierSchedulePage: React.FC<{ onBack: () => void; onLogout: () => void }> = ({ onBack, onLogout }) => {
  const [tab, setTab] = useState<DashboardTab>('overview');
  const [profile, setProfile] = useState<SupplierProfile | null>(null);
  const [people, setPeople] = useState<Practitioner[]>([]);
  const [bookings, setBookings] = useState<BookingRecord[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [rules, setRules] = useState<ScheduleRule[]>(defaultRules());
  const [loading, setLoading] = useState(true);
  const [scheduleLoading, setScheduleLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [memberEditor, setMemberEditor] = useState<Practitioner | 'new' | null>(null);

  useEffect(() => {
    setLoading(true);
    Promise.all([platformApi.supplierProfile(), platformApi.supplierPractitioners(), platformApi.supplierBookings()])
      .then(([supplier, team, supplierBookings]) => { setProfile(supplier); setPeople(team); setBookings(supplierBookings); setSelectedId(team[0]?.id ?? null); })
      .catch((requestError) => setError(getApiErrorMessage(requestError)))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    if (!selectedId || tab !== 'schedule') return;
    setScheduleLoading(true); setError(''); setMessage('');
    platformApi.practitionerSchedule(selectedId).then((result) => {
      const existing = new Map(result.map((rule) => [rule.dayOfWeek, rule]));
      setRules(defaultRules().map((fallback) => existing.get(fallback.dayOfWeek) || fallback));
    }).catch((requestError) => setError(getApiErrorMessage(requestError))).finally(() => setScheduleLoading(false));
  }, [selectedId, tab]);

  const upcoming = useMemo(() => bookings.filter((booking) => booking.status === 'CONFIRMED' || booking.status === 'PENDING'), [bookings]);
  const simulatedRevenue = useMemo(() => bookings.filter((booking) => booking.status !== 'CANCELLED').reduce((total, booking) => total + booking.totalAmount, 0), [bookings]);
  const formatMoney = (value: number) => new Intl.NumberFormat('vi-VN').format(value) + 'đ';
  const updateRule = (day: string, field: keyof ScheduleRule, value: string | number | boolean | null) => setRules((current) => current.map((rule) => rule.dayOfWeek === day ? { ...rule, [field]: value } : rule));
  const saveSchedule = async () => {
    if (!selectedId) return;
    setSaving(true); setError(''); setMessage('');
    try { setRules(await platformApi.replaceSchedule(selectedId, rules)); setMessage('Đã lưu lịch. Khung giờ trống cho khách hàng đã được cập nhật.'); }
    catch (requestError) { setError(getApiErrorMessage(requestError)); }
    finally { setSaving(false); }
  };
  const nav = [['overview', 'Tổng quan', LayoutDashboard], ['store', 'Gian hàng & dịch vụ', Store], ['bookings', 'Lịch hẹn', CalendarDays], ['team', 'Đội ngũ', UsersRound], ['schedule', 'Giờ làm việc', CalendarClock]] as const;

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#FFF0F3]"><div className="text-center"><LoaderCircle className="mx-auto h-8 w-8 animate-spin text-[#EB0F51]" /><p className="mt-3 text-sm font-bold text-slate-500">Đang mở không gian đối tác...</p></div></div>;

  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-4 py-4 sm:px-6"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm font-extrabold text-slate-600 hover:text-[#EB0F51]"><ArrowLeft className="h-4 w-4" /> Trang chủ</button><span className="text-lg font-black">Beauty<span className="text-[#EB0F51]">Link</span> <span className="text-xs text-slate-400">Partner</span></span><button type="button" onClick={onLogout} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-black text-rose-600 transition hover:bg-rose-600 hover:text-white"><LogOut className="h-4 w-4" /><span className="hidden sm:inline">Đăng xuất</span></button></div></header>
    <div className="mx-auto grid max-w-[1440px] lg:grid-cols-[250px_1fr]">
      <aside className="border-b border-slate-200 bg-white p-4 lg:min-h-[calc(100vh-65px)] lg:border-b-0 lg:border-r lg:p-5">
        <div className="mb-5 hidden rounded-2xl bg-[#FFF0F3] p-4 lg:block"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-[#EB0F51] shadow-sm"><Store className="h-5 w-5" /></span><div className="min-w-0"><p className="truncate text-sm font-black">{profile?.name}</p><p className="truncate text-[11px] text-slate-500">{profile?.businessType}</p></div></div></div>
        <nav className="flex gap-2 overflow-x-auto lg:block lg:space-y-1">{nav.map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-sm font-extrabold transition lg:w-full ${tab === key ? 'bg-[#EB0F51] text-white shadow-md shadow-pink-600/15' : 'text-slate-500 hover:bg-pink-50 hover:text-[#B42D58]'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
        <div className="mt-6 hidden rounded-2xl border border-slate-200 p-4 lg:block"><p className="text-xs font-black">Cần hỗ trợ?</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Đội ngũ BeautyLink sẵn sàng hỗ trợ thiết lập gian hàng.</p><button className="mt-3 text-xs font-black text-[#EB0F51]">Liên hệ hỗ trợ →</button></div>
      </aside>
      <main className="min-w-0 p-4 sm:p-6 lg:p-9">
        {profile?.verificationStatus === 'PENDING' && <div className="mb-6 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><Clock3 className="mt-0.5 h-5 w-5 shrink-0" /><div><p className="text-sm font-black">Hồ sơ đang chờ xác minh</p><p className="mt-1 text-xs leading-5 text-amber-800">Bạn có thể thiết lập đội ngũ và lịch ngay. Gian hàng chỉ hiển thị với khách sau khi BeautyLink duyệt hồ sơ.</p></div></div>}
        {error && <div role="alert" className="mb-5 flex items-center justify-between rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700"><span>{error}</span><button onClick={() => setError('')}><X className="h-4 w-4" /></button></div>}
        {tab === 'overview' && <Overview profile={profile} upcoming={upcoming.length} team={people.length} revenue={formatMoney(simulatedRevenue)} bookings={bookings} onNavigate={setTab} />}
        {tab === 'store' && profile && <SupplierStorePage profile={profile} onProfileUpdated={setProfile} />}
        {tab === 'bookings' && <Bookings bookings={bookings} formatMoney={formatMoney} />}
        {tab === 'team' && <Team people={people} onAdd={() => setMemberEditor('new')} onEdit={setMemberEditor} onSchedule={(id) => { setSelectedId(id); setTab('schedule'); }} />}
        {tab === 'schedule' && <ScheduleEditor people={people} selectedId={selectedId} setSelectedId={setSelectedId} rules={rules} updateRule={updateRule} save={saveSchedule} loading={scheduleLoading} saving={saving} message={message} />}
      </main>
    </div>
    {memberEditor && <MemberModal person={memberEditor === 'new' ? null : memberEditor} onClose={() => setMemberEditor(null)} onSaved={(person) => { setPeople((current) => memberEditor === 'new' ? [...current, person] : current.map((item) => item.id === person.id ? person : item)); setSelectedId(person.id); setMemberEditor(null); setMessage(memberEditor === 'new' ? 'Đã thêm chuyên viên với lịch mặc định Thứ Hai–Thứ Bảy.' : 'Đã cập nhật hồ sơ chuyên viên.'); }} />}
  </div>;
};

function Overview({ profile, upcoming, team, revenue, bookings, onNavigate }: { profile: SupplierProfile | null; upcoming: number; team: number; revenue: string; bookings: BookingRecord[]; onNavigate: (tab: DashboardTab) => void }) {
  const completed = bookings.filter((booking) => booking.status === 'COMPLETED').length;
  const cancelled = bookings.filter((booking) => booking.status === 'CANCELLED').length;
  const completionRate = bookings.length ? Math.round((completed / bookings.length) * 100) : 0;
  const cards = [[bookings.length, 'Tổng lịch hẹn', BarChart3, 'text-blue-600 bg-blue-50'], [upcoming, 'Lịch sắp tới', CalendarDays, 'text-violet-600 bg-violet-50'], [`${completionRate}%`, 'Tỷ lệ hoàn thành', TrendingUp, 'text-amber-600 bg-amber-50'], [revenue, 'Giá trị đơn (mô phỏng)', CircleDollarSign, 'text-emerald-600 bg-emerald-50']] as const;
  const statusData = [
    { label: 'Sắp tới', value: upcoming, color: 'bg-blue-500' },
    { label: 'Hoàn thành', value: completed, color: 'bg-emerald-500' },
    { label: 'Đã hủy', value: cancelled, color: 'bg-rose-400' },
  ];
  const maxStatus = Math.max(1, ...statusData.map((item) => item.value));
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#EB0F51]">Tổng quan gian hàng</p><h1 className="mt-2 text-3xl font-black">Xin chào, {profile?.name}</h1><p className="mt-2 flex items-center gap-1 text-sm text-slate-500"><MapPin className="h-4 w-4 text-[#D28474]" />{profile?.addressLine}, {profile?.locationName}</p></div><span className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-xs font-black ${profile?.verificationStatus === 'VERIFIED' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{profile?.verificationStatus === 'VERIFIED' ? <BadgeCheck className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}{profile?.verificationStatus === 'VERIFIED' ? 'Đã xác minh' : 'Chờ xác minh'}</span></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([value, label, Icon, color]) => <div key={label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></div><p className="mt-5 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-semibold text-slate-500">{label}</p></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Lịch hẹn gần đây</h2><p className="text-xs text-slate-500">Dữ liệu cập nhật trực tiếp từ lịch khách đã đặt.</p></div><button onClick={() => onNavigate('bookings')} className="text-xs font-black text-[#EB0F51]">Xem tất cả</button></div><div className="mt-4 space-y-2">{bookings.slice(0, 4).map((booking) => <BookingRow key={booking.id} booking={booking} />)}{bookings.length === 0 && <Empty title="Chưa có lịch hẹn" text="Lịch mới của khách sẽ xuất hiện tại đây." />}</div></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-[#EB0F51]" /><h2 className="font-black">Phân bổ trạng thái</h2></div><p className="mt-1 text-[11px] text-slate-500">Tổng hợp trên {bookings.length} lịch hẹn hiện có.</p><div className="mt-6 space-y-5">{statusData.map((item) => <div key={item.label}><div className="mb-2 flex justify-between text-xs"><span className="font-bold text-slate-600">{item.label}</span><strong>{item.value}</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.color}`} style={{ width: `${item.value ? Math.max(8, (item.value / maxStatus) * 100) : 0}%` }} /></div></div>)}</div><p className="mt-6 rounded-xl bg-amber-50 p-3 text-[10px] leading-4 text-amber-800">Do thanh toán đang mô phỏng, “giá trị đơn” chỉ phục vụ trình diễn và chưa phải doanh thu thực nhận.</p></section></div>
    <section className="mt-6 rounded-3xl bg-slate-900 p-6 text-white shadow-sm"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><Settings2 className="h-6 w-6 text-pink-300" /><h2 className="mt-3 text-xl font-black">Tăng khả năng được tìm thấy</h2><p className="mt-2 text-xs leading-5 text-slate-300">Hoàn thiện ảnh gian hàng, GPS, dịch vụ và lịch làm việc để khách có đủ thông tin trước khi đặt.</p></div><button onClick={() => onNavigate('store')} className="flex min-w-48 items-center justify-between rounded-xl bg-white px-4 py-3 text-xs font-black text-slate-900">Quản lý gian hàng <ChevronRight className="h-4 w-4" /></button></div></section></>;
}

function Bookings({ bookings, formatMoney }: { bookings: BookingRecord[]; formatMoney: (value: number) => string }) {
  return <section><PageTitle eyebrow="Vận hành" title="Quản lý lịch hẹn" description="Danh sách lịch hẹn được đặt tại cơ sở của bạn." /><div className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{bookings.length ? bookings.map((booking) => <div key={booking.id} className="grid gap-3 border-b border-slate-100 p-5 last:border-0 md:grid-cols-[1.3fr_1fr_0.8fr_auto] md:items-center"><div><p className="text-sm font-black">{booking.serviceName}</p><p className="mt-1 text-xs text-slate-500">{booking.bookingCode} · {booking.practitionerName}</p></div><p className="text-xs font-bold">{booking.appointmentDate} · {booking.startTime.slice(0, 5)}</p><p className="text-sm font-black">{formatMoney(booking.totalAmount)}</p><Status status={booking.status} /></div>) : <Empty title="Chưa có lịch hẹn" text="Khi khách đặt dịch vụ, thông tin sẽ xuất hiện tại đây." />}</div></section>;
}

function Team({ people, onAdd, onEdit, onSchedule }: { people: Practitioner[]; onAdd: () => void; onEdit: (person: Practitioner) => void; onSchedule: (id: number) => void }) {
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><PageTitle eyebrow="Nhân sự" title="Đội ngũ chuyên viên" description="Thêm chuyên viên, tải ảnh đại diện và cấu hình lịch làm việc riêng." /><button onClick={onAdd} className="inline-flex items-center gap-2 rounded-xl bg-[#EB0F51] px-4 py-3 text-xs font-black text-white hover:bg-[#B42D58]"><Plus className="h-4 w-4" /> Thêm chuyên viên</button></div><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{people.map((person) => <article key={person.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center overflow-hidden rounded-2xl bg-pink-50 text-[#EB0F51]">{person.avatarUrl ? <img src={person.avatarUrl} alt={person.displayName} className="h-full w-full object-cover" /> : <UserRound className="h-6 w-6" />}</span><div><h3 className="font-black">{person.displayName}</h3><p className="mt-1 text-xs text-slate-500">{person.specialty || 'Chuyên viên làm đẹp'}</p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={() => onEdit(person)} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 py-2.5 text-xs font-black text-slate-600 hover:bg-slate-50"><Pencil className="h-4 w-4" /> Hồ sơ</button><button onClick={() => onSchedule(person.id)} className="flex items-center justify-center gap-2 rounded-xl border border-pink-200 py-2.5 text-xs font-black text-[#B42D58] hover:bg-pink-50"><CalendarClock className="h-4 w-4" /> Lịch làm</button></div></article>)}</div></section>;
}

function ScheduleEditor({ people, selectedId, setSelectedId, rules, updateRule, save, loading, saving, message }: { people: Practitioner[]; selectedId: number | null; setSelectedId: (id: number) => void; rules: ScheduleRule[]; updateRule: (day: string, field: keyof ScheduleRule, value: string | number | boolean | null) => void; save: () => void; loading: boolean; saving: boolean; message: string }) {
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><PageTitle eyebrow="Khả dụng" title="Giờ làm việc" description="Thiết lập ngày làm, giờ nghỉ và độ dài mỗi khung đặt lịch." /><button onClick={save} disabled={saving || loading || !selectedId} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-xs font-black text-white hover:bg-[#B42D58] disabled:opacity-40">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />} Lưu lịch</button></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[230px_1fr]"><aside className="h-fit rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><p className="px-3 pb-2 pt-1 text-[11px] font-black uppercase tracking-wider text-slate-400">Chuyên viên</p>{people.map((person) => <button key={person.id} onClick={() => setSelectedId(person.id)} className={`mb-1 flex w-full items-center gap-3 rounded-2xl p-3 text-left ${selectedId === person.id ? 'bg-pink-50 text-[#B42D58]' : 'hover:bg-slate-50'}`}><UserRound className="h-4 w-4" /><span><span className="block text-xs font-black">{person.displayName}</span><span className="block text-[10px] text-slate-500">{person.specialty}</span></span></button>)}</aside>
    <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6">{loading ? <div className="grid h-64 place-items-center"><LoaderCircle className="h-7 w-7 animate-spin text-[#EB0F51]" /></div> : <><div className="mb-3 hidden grid-cols-[125px_repeat(5,1fr)] gap-2 px-3 text-[10px] font-black uppercase tracking-wider text-slate-400 sm:grid"><span>Ngày</span><span>Bắt đầu</span><span>Kết thúc</span><span>Nghỉ từ</span><span>Nghỉ đến</span><span>Khung giờ</span></div><div className="space-y-2">{rules.map((rule) => { const label = days.find(([key]) => key === rule.dayOfWeek)?.[1] || rule.dayOfWeek; return <div key={rule.dayOfWeek} className={`grid gap-3 rounded-2xl border p-3 sm:grid-cols-[110px_1fr] sm:items-center ${rule.active ? 'border-slate-200' : 'border-slate-100 bg-slate-50 opacity-65'}`}><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={rule.active} onChange={(event) => updateRule(rule.dayOfWeek, 'active', event.target.checked)} className="h-4 w-4 accent-[#EB0F51]" />{label}</label><div className="grid grid-cols-2 gap-2 sm:grid-cols-5"><Time value={rule.startTime} disabled={!rule.active} onChange={(value) => updateRule(rule.dayOfWeek, 'startTime', value)} /><Time value={rule.endTime} disabled={!rule.active} onChange={(value) => updateRule(rule.dayOfWeek, 'endTime', value)} /><Time value={rule.breakStart || ''} disabled={!rule.active} onChange={(value) => updateRule(rule.dayOfWeek, 'breakStart', value || null)} /><Time value={rule.breakEnd || ''} disabled={!rule.active} onChange={(value) => updateRule(rule.dayOfWeek, 'breakEnd', value || null)} /><select disabled={!rule.active} value={rule.slotMinutes} onChange={(event) => updateRule(rule.dayOfWeek, 'slotMinutes', Number(event.target.value))} className="rounded-xl border border-slate-200 px-2 py-2 text-xs font-bold"><option value={30}>30 phút</option><option value={45}>45 phút</option><option value={60}>60 phút</option><option value={90}>90 phút</option></select></div></div>; })}</div>{message && <p className="mt-4 flex items-center gap-2 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-5 w-5" />{message}</p>}</>}</div></div></section>;
}

function MemberModal({ person, onClose, onSaved }: { person: Practitioner | null; onClose: () => void; onSaved: (person: Practitioner) => void }) {
  const [form, setForm] = useState({ displayName: person?.displayName || '', specialty: person?.specialty || '', bio: person?.bio || '', avatarUrl: person?.avatarUrl || '' }); const [saving, setSaving] = useState(false); const [uploadingAvatar, setUploadingAvatar] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { onSaved(person ? await platformApi.updatePractitioner(person.id, form) : await platformApi.createPractitioner(form)); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setSaving(false); } };
  const uploadAvatar = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setUploadingAvatar(true); setError(''); try { const avatarUrl = await prepareImageUpload(file); setForm((current) => ({ ...current, avatarUrl })); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : 'Không thể xử lý ảnh.'); } finally { setUploadingAvatar(false); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[#EB0F51]">Đội ngũ</p><h2 className="mt-1 text-xl font-black">{person ? 'Chỉnh sửa chuyên viên' : 'Thêm chuyên viên'}</h2><p className="mt-1 text-xs text-slate-500">{person ? 'Cập nhật ảnh đại diện và thông tin hiển thị.' : 'Hệ thống sẽ tạo lịch mặc định để bạn chỉnh sửa ngay.'}</p></div><button onClick={onClose} className="rounded-full p-2 hover:bg-slate-100"><X className="h-5 w-5" /></button></div><form onSubmit={submit} className="mt-6 space-y-4"><div className="flex items-center gap-4 rounded-2xl border border-dashed border-pink-200 bg-pink-50/40 p-3"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white text-pink-300">{form.avatarUrl ? <img src={form.avatarUrl} alt="Ảnh chuyên viên" className="h-full w-full object-cover" /> : <UserRound className="h-7 w-7" />}</div><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-black text-[#B42D58] shadow-sm">{uploadingAvatar ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <ImagePlus className="h-4 w-4" />} Tải ảnh đại diện<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadAvatar} className="sr-only" /></label></div><label className="block"><span className="mb-1 block text-xs font-black">Tên hiển thị *</span><input required value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} className="field" /></label><label className="block"><span className="mb-1 block text-xs font-black">Chuyên môn</span><input value={form.specialty} onChange={(e) => setForm({ ...form, specialty: e.target.value })} placeholder="Trang điểm cô dâu, chăm sóc da..." className="field" /></label><label className="block"><span className="mb-1 block text-xs font-black">Giới thiệu</span><textarea rows={3} value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} className="field resize-none" /></label>{error && <p className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<button disabled={saving || uploadingAvatar} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#EB0F51] py-3 text-xs font-black text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : person ? <Save className="h-4 w-4" /> : <Plus className="h-4 w-4" />} {person ? 'Lưu hồ sơ' : 'Thêm vào đội ngũ'}</button></form></div></div>;
}

function PageTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#EB0F51]">{eyebrow}</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-slate-500">{description}</p></div>; }
function Time({ value, onChange, disabled }: { value: string; onChange: (value: string) => void; disabled: boolean }) { return <input type="time" value={value?.slice(0, 5)} onChange={(event) => onChange(event.target.value)} disabled={disabled} className="min-w-0 rounded-xl border border-slate-200 px-2 py-2 text-xs font-bold disabled:bg-slate-100" />; }
function Status({ status }: { status: BookingRecord['status'] }) { const styles = status === 'CONFIRMED' ? 'bg-emerald-50 text-emerald-700' : status === 'CANCELLED' ? 'bg-rose-50 text-rose-700' : status === 'COMPLETED' ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-700'; const label = { CONFIRMED: 'Đã xác nhận', CANCELLED: 'Đã hủy', COMPLETED: 'Hoàn thành', PENDING: 'Chờ xác nhận' }[status]; return <span className={`w-fit rounded-full px-3 py-1.5 text-[10px] font-black ${styles}`}>{label}</span>; }
function BookingRow({ booking }: { booking: BookingRecord }) { return <div className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-[#EB0F51]"><BriefcaseBusiness className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-xs font-black">{booking.serviceName}</p><p className="mt-0.5 text-[10px] text-slate-500">{booking.appointmentDate} · {booking.startTime.slice(0, 5)} · {booking.practitionerName}</p></div></div><Status status={booking.status} /></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="px-6 py-14 text-center"><CalendarClock className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 text-sm font-black">{title}</p><p className="mt-1 text-xs text-slate-500">{text}</p></div>; }
